---

- hosts: all
  become: true
  tasks:

  - name:  my update repository index
    apt:
      update_cache: yes

  - name: my install apache2 package
    apt:
      name: apache2
      state: latest

  - name: my add php support for apache
    apt:
      name: libapache2-mod-php
      atate: latest
